spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
      bindings:
        consumer:
          destination: demoMicroservice
          contentType: application/json
        producer:
          destination: demoMicroservice
          contentType: application/json
   data:
     elasticsearch:
       cluster-name: elastic-local-cluster
       cluster-nodes: localhost:9300
server:
  port: 8091
  
          
          
            
