spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9093
      bindings:
        consumer:
          destination: demoMicroservice
          contentType: application/json
          group: customerGroupD1
        producer:
          destination: demoMicroservice
          contentType: application/json
          group: customerGroupD1
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
server:
  port: 8111
  
          
          
            
